spring:
  profiles:
    active:
    - dev
  application:
    name: ai
  ai:
    ollama:
      base-url: http://ollama:11434/
      chat:
        options:
          model: llama3.2
          temperature: 0.7
server:
  servlet:
    context-path: /ai
