spring:
  ai:
    ollama:
      base-url: http://ollama:11434/
      init:
        pull-model-strategy: when-missing

management:
  endpoints:
    web:
      exposure:
        include: health,info,env,beans,conditions
  endpoint:
    env:
      show-values: ALWAYS