server:
  servlet:
    context-path: /ai

spring:
  application:
    name: ai
  ai:
    ollama:
      base-url: http://ollama:11434/
      chat:
        options:
          model: qwen2.5:1.5b
          temperature: 0.7
      embedding:
        options:
          model: embeddinggemma
      init:
        pull-model-strategy: never

    mcp:
      client:
        type: ASYNC
        toolcallback:
          enabled: true
        sse:
          connections:
            server1:
              url: https://gitmcp.io/spring-projects/spring-ai

    vectorstore:
      pgvector:
        index-type: HNSW
        distance-type: COSINE_DISTANCE
        dimensions: 768 # embeddinggemma model dimension is 768
        max-document-batch-size: 10000 # Optional: Maximum number of documents per batch
        remove-existing-vector-store-table: true

  datasource:
    url: jdbc:h2:mem:testdb
