spring:
  ai:
    ollama:
      #base-url: http://localhost:11434/
      init:
        pull-model-strategy: when-missing

springdoc:
  swagger-ui:
    doc-expansion: none
    tags-sorter: alpha

management:
  endpoints:
    web:
      exposure:
        include: health,info,env,beans,conditions
  endpoint:
    env:
      show-values: ALWAYS