server:
  servlet:
    context-path: /ai

spring:
  profiles:
    active:
    - dev
  application:
    name: ai
  ai:
    ollama:
      base-url: http://ollama:11434/
      chat:
        options:
          model: qwen2.5:1.5b
          temperature: 0.7
      embedding:
        options:
          model: bge-m3
      init:
        pull-model-strategy: when_missing

    mcp:
      client:
        type: ASYNC
        toolcallback:
          enabled: true
        sse:
          connections:
            server1:
              url: https://gitmcp.io/spring-projects/spring-ai
