spring:
  profiles:
    active:
    - dev
  application:
    name: ai
  ai:
    ollama:
      base-url: http://ollama:11434/
      chat:
        options:
          model: qwen2.5:1.5b
          temperature: 0.7
      embedding:
        options:
          model: bge-m3
server:
  servlet:
    context-path: /ai
