services:
  spring-ai-dev:
    image: mcr.microsoft.com/devcontainers/base:ubuntu
    container_name: spring-ai-dev
    depends_on:
      - ollama-dev
    ports:
      - "8080:8080"
    volumes:
      - ..:/workspaces/spring-ai:cached
    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity

  ollama-dev:
    hostname: ollama
    container_name: ollama-dev
    image: ollama/ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama-vol:/root/.ollama:cached

  postgres:
    image: pgvector/pgvector:pg18
    hostname: postgres
    container_name: postgres
    ports:
      - "5432:5432"
    volumes:
      - pg-data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: pgdb
      POSTGRES_USER: pguser
      POSTGRES_PASSWORD: pguser_pw123!

#  open-webui:
#    image: ghcr.io/open-webui/open-webui:${WEBUI_DOCKER_TAG-main}
#    container_name: open-webui
#    depends_on:
#      - ollama-dev
#    environment:
#      - 'OLLAMA_BASE_URL=http://ollama:11434'
#    ports:
#      - "3000:8080"


volumes:
  ollama-vol: {}
  pg-data: {}